# textlintでの文法チェックのワークフロー
name: Lint

# Reviewdogでの指摘を有効に使うため、pull requestでのみ有効
on:
  pull_request:
    # Pull Requestかつ
    # 以下のファイルに変更があった場合、このWorkflowを実行
    paths:
      - "prh.yml"
      - ".textlintrc"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/lint.yaml"
      - "**.tex"

jobs:
  lint:
    name: textlint / reviewwdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          fail_on_error: true
          textlint_flags: "*/*.tex"
